### ISSUE TITLE
Show fingerprint of GPG key, mention GPG key transition in release notes

### ISSUE THREAD

**Issue by tyll** [gobby/gobby#107]
It seems that the recent download uses a new GPG key for signatures, please properly announce it and mention the correct key on the download page:
https://github.com/gobby/gobby/wiki/Download
or
https://gobby.github.io/

**Comment by aburgm** [comment]
Thanks for the heads up! I indeed made a new GPG key a while ago because the previous one was still 1024-bit DSA. The new key is signed by the old key, so in principle people should be able to verify that the new key belongs to the same person that the old key did.

I added a note on gobby.github.io and added the IDs and fingerprints of the keys on the download page.

**Comment by tyll** [comment]
Thank you very much
